---
title: "African_authors_detailed_list - Mental Health Screen tool"
author: "Reinpeter"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    number_sections: yes
  pdf_document:
    number_sections: yes
  word_document: 
    number_sections: yes
---

# **Introduction**

```{r setup, results="hide", include=FALSE}

## Set Chunk requirements
knitr::opts_chunk$set(#include = TRUE,
                      echo=FALSE, message = FALSE, warning = FALSE)

```

```{r setting working directory, include=FALSE}

## Setting work directory

setwd(".")

```

```{r loading relevant packages, include=FALSE}

#library we need
libs_mental_health <- c("googledrive", "tidyverse", "janitor", "knitr", "readxl", "writexl", "DiagrammeR", "DiagrammeRsvg",
                        "rsvg")

#install missing libraries

inatalled_libs_mental_health <- libs_mental_health  %in% rownames(installed.packages())
if (any(inatalled_libs_mental_health==F)) {
  install.packages(libs_mental_health[!inatalled_libs_mental_health])
}

#load libraries

invisible(lapply(libs_mental_health, library, character.only=T))


```

```{r googledrive downloading data, include=FALSE}

 drive_auth(#email = "guest360@aphrc.org"
           )

  #drive_user()

  mental_file_id <- drive_find(shared_drive = c(shared_drive_find(pattern = "Data Science Programs")$id),
           q = c("name contains 'Mental Health'",
                 "mimeType = 'application/vnd.google-apps.shortcut'")) #search for a specific set of shared drives, use the query string q

  list_files_shortcut_folder <- drive_ls(path = mental_file_id$id, q = c("name = 'African_authors_detailed_list (2) (1).xlsx'"))
  
  
  mental_local_download <- drive_download(list_files_shortcut_folder$id, overwrite = TRUE)
  
```

# **Inclusion/Exclusion**

```{r reading data, include=FALSE}

  mental_health_publications <- read_excel(paste0(mental_local_download$local_path), sheet = "African_authors_detailed_list (")%>%
  janitor::clean_names()

```


```{r distinct titles, include=FALSE}

mental_health_publications_distinct <- mental_health_publications%>%
  mutate(source_title = str_to_title(source_title) #
         ,source_title = gsub("\\.$", "", source_title) #Removing period at end of string
         )%>%
  distinct(source_title, .keep_all = TRUE)

```


```{r inclusion data}

mental_health_publications_inclusion_final <- mental_health_publications_distinct%>%
  filter(str_detect(source_title, regex("psychosis|depression|anxiety|depressive|depressed|
                                        \\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia|
                                       \\bmental health disorders\\b|\\bmental disorders\\b|
                                        \\bmental health disorder\\b|\\bmental disorder\\b|
                                        \\bmental health problems\\b|\\bmental problems\\b|
                                        \\bmental health problem\\b|\\bmental problem\\b|
                                       \\bmental health illness\\b|\\bmental illness\\b|\\bmental health conditions\\b",
                                        ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex(paste(c("psychosis", "depression", "anxiety","depressive" , "depressed",
                                                    "\\bsocial phobia\\b", "phobia", "\\bpanic disorder\\b", "agoraphobia",
                                                    "\\bmental health disorders\\b","\\bmental disorders\\b",
                                                    "\\bmental health disorder\\b","\\bmental disorder\\b",
                                                    "\\bmental health problems\\b","\\bmental problems\\b",
                                                    "\\bmental health problem\\b","\\bmental problem\\b",
                                                    "\\bmental health illness\\b","\\bmental illness\\b",
                                                    "\\bmental health conditions\\b"),
                                                         collapse = '|'),
                                        ignore_case = TRUE) )
         )

```


```{r exclusion data}

mental_health_publications_exclusion_final <- mental_health_publications_distinct%>%
  filter(!str_detect(source_title, regex("psychosis|depression|anxiety|depressive|depressed|
                                        \\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia|
                                       \\bmental health disorders\\b|\\bmental disorders\\b|
                                        \\bmental health disorder\\b|\\bmental disorder\\b|
                                        \\bmental health problem\\b|\\bmental problem\\b|
                                        \\bmental health problems\\b|\\bmental problems\\b|
                                       \\bmental health illness\\b|\\bmental illness\\b|\\bmental health conditions\\b",
                                        ignore_case = TRUE)) &
         !str_detect(source_fields_of_study,  regex(paste(c("psychosis", "depression", "anxiety","depressive" , "depressed",
                                                    "\\bsocial phobia\\b", "phobia", "\\bpanic disorder\\b", "agoraphobia",
                                                    "\\bmental health disorders\\b","\\bmental disorders\\b",
                                                    "\\bmental health disorder\\b","\\bmental disorder\\b",
                                                    "\\bmental health problems\\b","\\bmental problems\\b",
                                                    "\\bmental health problem\\b","\\bmental problem\\b",
                                                    "\\bmental health illness\\b","\\bmental illness\\b",
                                                    "\\bmental health conditions\\b"),
                                                         collapse = '|'),
                                        ignore_case = TRUE) )
         )

```


```{r longitudinal cross sectional reviews Randomized trials}

longitudinal_publications_final <- mental_health_publications_inclusion_final%>%
  filter(str_detect(source_title, regex("longitudinal|\\bcohort study\\b|\\bpanel study\\b",ignore_case = TRUE)) |
         str_detect(source_fields_of_study, regex("longitudinal|\\bcohort study\\b|\\bpanel study\\b",ignore_case = TRUE) )
         )

reviews_publications_final <- mental_health_publications_inclusion_final%>%
  filter(str_detect(source_title, regex("\\bsystematic review\\b|\\bmeta\\b|\\breview\\b|\\bcase report\\b|\\bcase reports\\b|\\boverview\\b|\\bliterature\\b", ignore_case = TRUE)) |
         str_detect(source_fields_of_study, regex("\\bsystematic review\\b|\\bmeta\\b|\\breview\\b|\\bcase report\\b|\\bcase reports\\b|\\boverview\\b|\\bliterature\\b", ignore_case = TRUE) ),
         !str_detect(source_title, regex("longitudinal|\\bcohort study\\b|\\bpanel study\\b", ignore_case = TRUE)) &
         !str_detect(source_fields_of_study, regex("longitudinal|\\bcohort study\\b|\\bpanel study\\b", ignore_case = TRUE) )
         )

randomized_trials_publications_final <- mental_health_publications_inclusion_final%>%
  filter(str_detect(source_title, regex("placebo|\\bblind\\b|\\brandomised controlled trial\\b|\\brandomized controlled trial\\b",
                                        ignore_case = TRUE)) |
         str_detect(source_fields_of_study, regex("placebo|\\bblind\\b|\\brandomised controlled trial\\b|\\brandomized controlled trial\\b",ignore_case = TRUE) ),
         !str_detect(source_title, regex("\\bsystematic review\\b|\\bmeta\\b|\\breview\\b|\\bcase report\\b|\\bcase reports\\b|\\boverview\\b|\\bliterature\\b|longitudinal|\\bcohort study\\b|\\bpanel study\\b", ignore_case = TRUE)) &
         !str_detect(source_fields_of_study, regex("\\bsystematic review\\b|\\bmeta\\b|\\breview\\b|\\bcase report\\b|\\bcase reports|\\boverview\\b|\\bliterature\\b|longitudinal|\\bcohort study\\b|\\bpanel study\\b", ignore_case = TRUE) )
         )

cross_sectional_publications_final <- mental_health_publications_inclusion_final%>%
  filter(!str_detect(source_title, regex("longitudinal|\\bcohort study\\b|\\bpanel study\\b|placebo|\\bblind\\b|\\brandomised controlled trial\\b|\\brandomized controlled trial\\b|\\bsystematic review\\b|\\bmeta\\b|\\breview\\b|\\bcase report\\b|\\bcase reports\\b|\\boverview\\b|\\bliterature\\b", ignore_case = TRUE)) &
         !str_detect(source_fields_of_study, regex("longitudinal|\\bcohort study\\b|\\bpanel study\\b|placebo|\\bblind\\b|\\brandomised controlled trial\\b|\\brandomized controlled trial\\b|\\bsystematic review\\b|\\bmeta\\b|\\breview\\b|\\bcase report\\b|\\bcase reports\\b|\\boverview\\b|\\bliterature\\b", ignore_case = TRUE) )
         )

```


```{r systematic reviews meta analysis psychosis depression anxiety data}

reviews_psychosis_publications_final <- reviews_publications_final%>%
  filter(str_detect(source_title, regex("psychosis", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("psychosis", ignore_case = TRUE) )
         )

reviews_depression_publications_final <- reviews_publications_final%>%
  filter(str_detect(source_title, regex("depression|depressive|depressed", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("depression|depressive|depressed", ignore_case = TRUE) )
         )

reviews_anxiety_publications_final <- reviews_publications_final%>%
  filter(str_detect(source_title, regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                        ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                                   ignore_case = TRUE) )
         )

```

```{r longitudinal psychosis depression anxiety data}

longitudinal_psychosis_publications_final <- longitudinal_publications_final%>%
  filter(str_detect(source_title, regex("psychosis", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("psychosis", ignore_case = TRUE) )
         )

longitudinal_depression_publications_final <- longitudinal_publications_final%>%
  filter(str_detect(source_title, regex("depression|depressive|depressed", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("depression|depressive|depressed", ignore_case = TRUE) )
         )

longitudinal_anxiety_publications_final <- longitudinal_publications_final%>%
  filter(str_detect(source_title, regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                        ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                                   ignore_case = TRUE) )
         )

```


```{r randomized trials psychosis depression anxiety data}

randomized_trials_psychosis_publications_final <- randomized_trials_publications_final%>%
  filter(str_detect(source_title, regex("psychosis", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("psychosis", ignore_case = TRUE) )
         )

randomized_trials_depression_publications_final <- randomized_trials_publications_final%>%
  filter(str_detect(source_title, regex("depression|depressive|depressed", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("depression|depressive|depressed", ignore_case = TRUE) )
         )

randomized_trials_anxiety_publications_final <- randomized_trials_publications_final%>%
  filter(str_detect(source_title, regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                        ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                                   ignore_case = TRUE) )
         )

```


```{r cross-sectional psychosis depression anxiety data}

cross_sectional_psychosis_publications_final <- cross_sectional_publications_final%>%
  filter(str_detect(source_title, regex("psychosis", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("psychosis", ignore_case = TRUE) )
         )

cross_sectional_depression_publications_final <- cross_sectional_publications_final%>%
  filter(str_detect(source_title, regex("depression|depressive|depressed", ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("depression|depressive|depressed", ignore_case = TRUE) )
         )

cross_sectional_anxiety_publications_final <- cross_sectional_publications_final%>%
  filter(str_detect(source_title, regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                        ignore_case = TRUE)) |
         str_detect(source_fields_of_study,  regex("anxiety|\\bsocial phobia\\b|phobia|\\bpanic disorder\\b|agoraphobia",
                                                   ignore_case = TRUE) )
         )

```

# **FlowChart**

```{r flow chart}

data <- list(a=nrow(mental_health_publications), a_oldest=min(mental_health_publications$source_year_published),
             a_newest = max(mental_health_publications$source_year_published),
             b=nrow(mental_health_publications_distinct), b_oldest=min(mental_health_publications_distinct$source_year_published),
             b_newest = max(mental_health_publications_distinct$source_year_published),
             c=nrow(mental_health_publications_inclusion_final), 
             c_oldest=min(mental_health_publications_inclusion_final$source_year_published),
             c_newest = max(mental_health_publications_inclusion_final$source_year_published),
             d= nrow(cross_sectional_publications_final), d_oldest=min(cross_sectional_publications_final$source_year_published),
             d_newest = max(cross_sectional_publications_final$source_year_published),
             e = nrow(longitudinal_publications_final), e_oldest=min(longitudinal_publications_final$source_year_published),
             e_newest = max(longitudinal_publications_final$source_year_published),
             f = nrow(reviews_publications_final), f_oldest=min(reviews_publications_final$source_year_published),
             f_newest = max(reviews_publications_final$source_year_published),
             g = nrow(randomized_trials_publications_final), g_oldest=min(randomized_trials_publications_final$source_year_published),
             g_newest = max(randomized_trials_publications_final$source_year_published),
             h = nrow(cross_sectional_depression_publications_final),
             h_oldest=min(cross_sectional_depression_publications_final$source_year_published),
             h_newest = max(cross_sectional_depression_publications_final$source_year_published),
             i = nrow(cross_sectional_anxiety_publications_final),
             i_oldest=min(cross_sectional_anxiety_publications_final$source_year_published),
             i_newest = max(cross_sectional_anxiety_publications_final$source_year_published),
             j = nrow(cross_sectional_psychosis_publications_final),
             j_oldest=min(cross_sectional_psychosis_publications_final$source_year_published),
             j_newest = max(cross_sectional_psychosis_publications_final$source_year_published),
             k = nrow(longitudinal_depression_publications_final),
             k_oldest=min(longitudinal_depression_publications_final$source_year_published),
             k_newest = max(longitudinal_depression_publications_final$source_year_published),
             l = nrow(longitudinal_anxiety_publications_final), 
             l_oldest=min(longitudinal_anxiety_publications_final$source_year_published),
             l_newest = max(longitudinal_anxiety_publications_final$source_year_published),
             m = nrow(longitudinal_psychosis_publications_final), 
             m_oldest=min(longitudinal_psychosis_publications_final$source_year_published),
             m_newest = max(longitudinal_psychosis_publications_final$source_year_published),
             n = nrow(reviews_depression_publications_final), 
             n_oldest=min(reviews_depression_publications_final$source_year_published),
             n_newest = max(reviews_depression_publications_final$source_year_published),
             o = nrow(reviews_anxiety_publications_final), 
             o_oldest=min(reviews_anxiety_publications_final$source_year_published),
             o_newest = max(reviews_anxiety_publications_final$source_year_published),
             p = nrow(reviews_psychosis_publications_final), 
             p_oldest=min(reviews_psychosis_publications_final$source_year_published),
             p_newest = max(reviews_psychosis_publications_final$source_year_published),
             q = nrow(randomized_trials_depression_publications_final), 
             q_oldest=min(randomized_trials_depression_publications_final$source_year_published),
             q_newest = max(randomized_trials_depression_publications_final$source_year_published),
             r = nrow(randomized_trials_anxiety_publications_final), 
             r_oldest=min(randomized_trials_anxiety_publications_final$source_year_published),
             r_newest = max(randomized_trials_anxiety_publications_final$source_year_published),
             s = nrow(randomized_trials_psychosis_publications_final), 
             s_oldest=min(randomized_trials_psychosis_publications_final$source_year_published),
             s_newest = max(randomized_trials_psychosis_publications_final$source_year_published)
             )


g1 <- DiagrammeR::grViz("
digraph graph2 {

graph [layout = dot]

# node definitions
node [shape = rectangle, width = 4.5, fillcolor = Linen, fontsize=16]

data1 [label = 'Data', fillcolor = Beige]
a [label = '@@1']
b [label = '@@2']

compound=true;
subgraph cluster_filter {
node [shape=box];
label = 'Filter Data set';
 fontsize=18;
        fontname = 'helvetica-bold';
style=dashed;
{{ rank = same; filterby1 filterby2}}
  
filterby1 [label = 'Filter Title by\n Psychosis or\n Depression or Depressive or Depressed\n or Anxiety or Social Phobia or Phobia\n or Panic Disorder or Agoraphobia or\n Mental Health Disorder(s) or\n Mental Disorder(s) or Mental Problem(s)\n or Mental Health Problem(s)\n or Mental illness\n or Mental Health illness\n or Mental Health Conditions', width = 4.5]
filterby2 [label = 'Filter Field of Study by\n Psychosis or\n Depression or Depressive or Depressed\n or Anxiety or Social Phobia or Phobia\n or Panic Disorder or Agoraphobia or\n Mental Health Disorder(s) or\n Mental Disorder(s) or Mental Problem(s)\n or Mental Health Problem(s)\n or Mental illness\n or Mental Health illness\n or Mental Health Conditions', width = 4.5]
}

c [label = '@@3', shape = rectangle, width = 4.5]
d [label = '@@4', width = 4, shape=box]
e [label = '@@5', width = 4, shape=box]
f [label = '@@6', width = 4, shape=box]
g [label = '@@7', width = 4, shape=box]


h [label = '@@8', width = 3, shape=box]
i [label = '@@9', width = 3, shape=box]
j [label = '@@10', width = 3, shape=box]

k [label = '@@11', width = 3, shape=box]
l [label = '@@12', width = 3, shape=box]
m [label = '@@13', width = 3, shape=box]

n [label = '@@14', width = 3, shape=box]
o [label = '@@15', width = 3, shape=box]
p [label = '@@16', width = 3, shape=box]

q [label = '@@17', width = 3, shape=box]
r [label = '@@18', width = 3, shape=box]
s [label = '@@19', width = 3, shape=box]


# edge definitions with the node IDs

data1 -> a -> b

b -> filterby2 [lhead = cluster_filter]

filterby1 -> filterby2 [style = dashed, minlen=1.5, label = 'or', dir=both ]

filterby2 -> c [ltail = cluster_filter]

c -> {d, e, f, g}[minlen=2]

d -> e[minlen=1.5, style=invis];
{{ rank = same; d e }}
  
e -> f[minlen=1.5, style=invis];
{{ rank = same; e f }}
  
f -> g[minlen=1.5, style=invis];
  {{ rank = same; f g }}

d -> {h, i, j}

e -> {k, l, m}

f -> {n, o, p}

g -> {q, r, s}

h -> i[style=invis]
i -> j[style=invis]

k -> l[style=invis]
l -> m[style=invis]

n -> o[style=invis]
o -> p[style=invis]

q -> r[style=invis]
r -> s[style=invis]


}

[1]: paste0('Extracted African Authors List (n = ', data$a, ')', '\\n' , '\\n', '(oldest=', data$a_oldest, ', newest=', data$a_newest, ')')
[2]: paste0('Remove Dupliates on Title (n = ', data$b, ')', '\\n' , '\\n', '(oldest=', data$b_oldest, ', newest=', data$b_newest, ')')
[3]: paste0('Inclusion papers (n = ', data$c, ')', '\\n' , '\\n', '(oldest=', data$c_oldest, ', newest=', data$c_newest, ')')
[4]: paste0('Cross-Sectional  (n = ', data$d, ')', '\\n' , '\\n', '(oldest=', data$d_oldest, ', newest=', data$d_newest, ')')
[5]: paste0('Longitudinal  (n = ', data$e, ')', '\\n' , '\\n', '(oldest=', data$e_oldest, ', newest=', data$e_newest, ')')
[6]: paste0('Reviews(Systemic & Literature)/\\n Meta Analysis/Case Reports (n = ', data$f, ')' , '\\n', '\\n', '(oldest=', data$f_oldest, ', newest=', data$f_newest, ')')
[7]: paste0('Randomized Trials (n = ', data$g, ')', '\\n' , '\\n', '(oldest=', data$g_oldest, ', newest=', data$g_newest, ')')
[8]: paste0('Depression  (n = ', data$h, ')', '\\n' , '\\n', '(oldest=', data$h_oldest, ', newest=', data$h_newest, ')')
[9]: paste0('Anxiety  (n = ', data$i, ')', '\\n' , '\\n', '(oldest=', data$i_oldest, ', newest=', data$i_newest, ')')
[10]: paste0('Psychosis  (n = ', data$j, ')', '\\n' , '\\n', '(oldest=', data$j_oldest, ', newest=', data$j_newest, ')')
[11]: paste0('Depression  (n = ', data$k, ')', '\\n' , '\\n', '(oldest=', data$k_oldest, ', newest=', data$k_newest, ')')
[12]: paste0('Anxiety  (n = ', data$l, ')', '\\n' , '\\n', '(oldest=', data$l_oldest, ', newest=', data$l_newest, ')')
[13]: paste0('Psychosis  (n = ', data$m, ')', '\\n' , '\\n', '(oldest=', data$m_oldest, ', newest=', data$m_newest, ')')
[14]: paste0('Depression  (n = ', data$n, ')', '\\n' , '\\n', '(oldest=', data$n_oldest, ', newest=', data$n_newest, ')')
[15]: paste0('Anxiety  (n = ', data$o, ')', '\\n' , '\\n', '(oldest=', data$o_oldest, ', newest=', data$o_newest, ')')
[16]: paste0('Psychosis  (n = ', data$p, ')', '\\n' , '\\n', '(oldest=', data$p_oldest, ', newest=', data$p_newest, ')')
[17]: paste0('Depression  (n = ', data$q, ')', '\\n' , '\\n', '(oldest=', data$q_oldest, ', newest=', data$q_newest, ')')
[18]: paste0('Anxiety  (n = ', data$r, ')', '\\n' , '\\n', '(oldest=', data$r_oldest, ', newest=', data$r_newest, ')')
[19]: paste0('Psychosis  (n = ', data$s, ')', '\\n' , '\\n', '(oldest=', data$s_oldest, ', newest=', data$s_newest, ')')

")

g1

```

```{r}

  g1%>%
    export_svg %>% charToRaw %>% rsvg_png(file = "graph.png")

```

# **QA/QC Data**

## Random Selection of Exclusion Data

```{r random selection}

#Select 10 random numbers 50 times
inclusion_data <- mental_health_publications_inclusion_final%>%
  mutate(number= 1:n())

exclusion_data <- mental_health_publications_exclusion_final%>%
  mutate(number= 1:n())


set.seed(1111)
exclusion_random <- as.data.frame(replicate(50, sample(exclusion_data$number, 10, replace=FALSE)))%>%
  pivot_longer(everything(), 
               names_to = "times",
               names_prefix = "V",
    values_to = "random_number")%>%
  arrange(as.numeric(times))

inclusion_random <- as.data.frame(replicate(50, sample(inclusion_data$number, 10, replace=FALSE)))%>%
  pivot_longer(everything(), 
               names_to = "times",
               names_prefix = "V",
    values_to = "random_number")%>%
  arrange(as.numeric(times))


exclusion_data_random <- exclusion_random%>%
  left_join(exclusion_data, by = c("random_number" = "number"))

inclusion_data_random <- inclusion_random%>%
  left_join(inclusion_data, by = c("random_number" = "number"))

```


```{r saving inclusion and exclusion}

#readr::write_csv(mental_health_publications_final,"mental_health_publications_final.csv", na="")

inclusion_cross_sectional_data <- cross_sectional_publications_final%>%
  mutate(number= 1:n())

inclusion_longitudinal_data <- longitudinal_publications_final%>%
  mutate(number= 1:n())

inclusion_reviews_data <- reviews_publications_final%>%
  mutate(number= 1:n())

inclusion_randomized_trials_data <- randomized_trials_publications_final%>%
  mutate(number= 1:n())

writexl::write_xlsx(list(inclusion = inclusion_data,
                         exclusion = exclusion_data,
                         exclusion_random = exclusion_data_random,
                         inclusion_random = inclusion_data_random, 
                         inclusion_cross_sectional = inclusion_cross_sectional_data,
                         inclusion_longitudinal = inclusion_longitudinal_data,
                         inclusion_reviews_meta_case = inclusion_reviews_data,
                         inclusion__randomized_trials = inclusion_randomized_trials_data),
                    "mental_health_publications_inclusion_exclusion_final.xlsx")

```


